FROM python:3.11

WORKDIR /app

COPY . .
RUN pip install -r requirements-predictor.txt

ENV MODEL_PATH=/app/data/model.joblib

EXPOSE 8080
CMD ["uvicorn", "spam_app:app", "--host", "0.0.0.0", "--port", "8080"]
